# ===================================================================
# PENGATURAN UMUM
# ===================================================================
server:
  port: 8080

# ===================================================================
# KONFIGURASI PROFIL DEFAULT (untuk pengembangan lokal)
# ===================================================================
spring:
  # Konfigurasi koneksi ke database Neon Anda
  datasource:
    url: jdbc:postgresql://ep-damp-bush-a8v8nw5l-pooler.eastus2.azure.neon.tech/sitirahma_db?sslmode=require
    username: sitirahma_db_owner
    password: npg_awkWL6tu5EFn
  
  # Pengaturan JPA (Java Persistence API)
  jpa:
    hibernate:
      ddl-auto: update # Otomatis buat/update tabel saat aplikasi jalan
    show-sql: true # Tampilkan query SQL di konsol
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# PROFIL PRODUKSI (UNTUK RAILWAY/RENDER)
# ===================================================================
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    hibernate:
      ddl-auto: validate # Di produksi, hanya validasi, jangan ubah tabel
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect